FROM python:3.11-slim

WORKDIR /app

COPY requirements/requirements_inference.txt .
RUN pip install --no-cache-dir -r requirements_inference.txt

COPY src/ ./src
CMD ["python", "-u", "src/inference.py"]